### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by tobbbles** [toqueteos/ts3#4]
Sometimes I receive no error and an empty response. This happens in 1/5th of my requests, and I suspect it's down to the parsing of responses.

**Comment by toqueteos** [comment]
@mnzt Thanks for reporting it! I'll try to reproduce and make a fix for it ASAP

**Comment by mnzt** [comment]
Thanks for taking a look into it :) I'll probably be using this in production soon, so will be posting all the bugs that I find, and possibly putting in some pull requests.

**Comment by toqueteos** [comment]
May be related to #5

**Comment by toqueteos** [comment]
Just as a heads up, I'm working on a new version of ts3 (I'll probably leave the current one as v1 on gopkg.in) so if you have any suggestions they are more than welcome!
