### ISSUE TITLE
Ideas for V2

### ISSUE THREAD

**Issue by tobbbles** [toqueteos/ts3#6]
- Keypair response? Instead of the response being a string, it may be possible to pass back a struct of key pair values correlating to the command. Example:

```
// Unformatted
cluid=e2PADQ8fVw9MhhxdN3fjlUSSZTQ= cldbid=3 name=Toby\son\slinux

// Formatted
{
  {"cluid": "e2PADQ8fVw9MhhxdN3fjlUSSZTQ="},
  {"cldbid": "3"},
  {"name": "Toby\son\slinux"},
}
```

Here is some code I use to do something similar to this.

```
//Response contains the formatting for telnet responses in a key:pair format
type Response struct {
    Key   string
    Value string
}

//FmtResponse takes a string response from the ServerQuery and returns a formatted string array
func FmtResponse(input string) ([]Response, error) {
    if input != "" {

        var ResponseList []Response

        fields := strings.Fields(input)
        for _, e := range fields {
            keyvalue := strings.SplitN(e, "=", 2)
            new := Response{
                Key:   Sanitize(keyvalue[0]),
                Value: Sanitize(keyvalue[1]),
            }
            newList := append(ResponseList, new)
            ResponseList = newList
        }
        //Broke out of for loop and returns list
        return ResponseList, nil
    }
    return nil, errors.New("input is empty")
}
```
- Parsing of response strings. Example:

```
// Unparsed
Toby\son\slinux

//Parsed
Toby on linux
```

Here is the code I use to do this:

```
//Sanitize trims spaces and replaces escape codes with their readable counterparts.
func Sanitize(input string) string {
    res := strings.TrimSpace(input)
    res = strings.Replace(res, `\s`, " ", -1)
    return res
}
```
- Channels for notifications? This way, to set up a notification listener it would be as simple as:

```
func listener(notif chan Notificaion) {
  for _, e := range notif {
    fmt.Printf("Notification: %s", e)
  }
}
```

These are just my ideas, and I'd love some feedback on them.

**Comment by toqueteos** [comment]
- Keypair response is a good idea!
- Parsing and Sanitizing is [already implemented](https://github.com/toqueteos/ts3/blob/master/helpers.go#L53-L74) but I may have forgotten to call them in the proper places.
- Returning a channel leads to potential leaks, I probably will use an iterator for that so you can easily opt-out for receiving notifications and avoid leaks altogether, we'll see.

**Comment by toqueteos** [comment]
@mnzt Little status update, I wasn't able to finish the library rework yet :sob:
I'm still working hard on it, once I release something I'll ping you so you can try and/or give me feedback about it ok?

**Comment by mnzt** [comment]
Sounds good, I've been writing up a few test programs to bench mark across multiple libraries, I'll let you know how it holds up. :)

**Comment by toqueteos** [comment]
Hello again @mnzt ! Because of how fucked up the API is I'm making methods for all ServerQuery commands :sob: If you give me a list of the ones you are interested I can finish those first.

**Comment by toqueteos** [comment]
Nevermind, I solved the problem! Also, notifications are working. Will try to upload changes later today.

**Comment by mnzt** [comment]
Hey @toqueteos, how's it going? I'd love to help out hacking on this, especially with wrapper methods for specific serverquery stuff. What's the news?

**Comment by toqueteos** [comment]
@mnzt News is I've been in Japan for last 15 days! All commands seem to work fine with the nwe system but `help` unless I do some serious endline detection. It may not be a good thing because who the heck would use help via ServerQuery for bots?

**Comment by mnzt** [comment]
Awesome! Help should be left, unless someone opens and issue and provides and good reason for it's use IMO
